export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_KUDOS = 'GET_KUDOS';
export const GET_GIVEN_KUDOS = 'GET_GIVEN_KUDOS';
export const GET_KUDOS_COUNT = 'GET_KUDOS_COUNT';
export const REDUCE_KUDO_COUNT = 'REDUCE_KUDO_COUNT';